"""Generate architecture graphs, diagrams, and metrics for a package.

Usage (from the repository root)::

    python -m tools.architecture.generate                 # -> docs/architecture/current
    python -m tools.architecture.generate --check         # exit 1 if outputs are stale

The whole output set is first rendered in memory by :func:`render` (a pure
function of the source tree and the options) and then written, or compared
byte for byte in ``--check`` mode. Nothing is timestamped and no absolute path
is written, so repeated runs on the same tree produce identical bytes.

A snapshot generated with ``--freeze`` carries a marker in its README; the
generator then refuses to overwrite it unless ``--overwrite-frozen`` is given.
``--check`` never writes and may be pointed at a frozen snapshot.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass, field
from importlib import metadata
from pathlib import Path

from . import TOOL_VERSION
from .calls import build_call_graph, scoped
from .classes import build_class_graph
from .imports import (aggregate_by_package, build_import_graph, containing_package,
                      excluded_modules, import_time_subgraph)
from .mermaid import call_flowchart, class_diagram, module_flowchart, package_flowchart
from .metrics import describe
from .model import dumps
from .report import render_metrics_md, render_readme
from .sources import Project

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATED_MARKER = "<!-- generated by tools.architecture -->"
FROZEN_MARKER = "<!-- architecture-snapshot: frozen -->"

#: Scoped call graphs: name -> root functions. The roots are the handlers the
#: ``tropoi`` CLI dispatches its subcommands to (static analysis cannot follow
#: the argparse ``set_defaults(_handler=...)`` dispatch itself). Overridable
#: with ``--call-root NAME=QUALIFIED.NAME``.
DEFAULT_CALL_ROOTS: dict[str, list[str]] = {
    "cli-run-bve": ["tropoi.cli.main._cmd_run_bve"],
    "cli-run-swe": ["tropoi.cli.main._cmd_run_swe"],
    "cli-run-pe": ["tropoi.cli.main._cmd_run_pe"],
    "cli-inspect": ["tropoi.cli.main._cmd_inspect"],
    "cli-gen": ["tropoi.cli.main._cmd_gen"],
}
DEFAULT_CALL_DEPTH = 4


@dataclass
class Options:
    src: str = "src"
    package: str = "tropoi"
    out: str = "docs/architecture/current"
    title: str = "current"
    call_roots: dict[str, list[str]] = field(default_factory=lambda: dict(DEFAULT_CALL_ROOTS))
    call_depth: int = DEFAULT_CALL_DEPTH
    source_commit: str | None = None     # full sha, verified by the caller
    generator_commit: str | None = None  # full sha, verified by the caller
    freeze: bool = False
    command: str = "python -m tools.architecture.generate"


def render(opts: Options, root: Path = REPO_ROOT) -> dict[str, str]:
    """All output files as ``{posix relative path: text}``."""
    project = Project(root / opts.src, opts.package)
    pkg = opts.package

    modules = build_import_graph(project)
    import_time = import_time_subgraph(modules)
    packages = aggregate_by_package(modules, project)
    classes = build_class_graph(project)
    calls, call_totals = build_call_graph(project)

    all_metrics = describe(modules.to_networkx())
    files: dict[str, str] = {}

    # -- graph data (neutral model) --
    files["graph/modules.json"] = dumps(modules.to_dict())
    files["graph/packages.json"] = dumps(packages.to_dict())
    files["graph/classes.json"] = dumps(classes.to_dict())
    files["graph/calls.json"] = dumps(calls.to_dict())

    # -- module diagrams --
    files["modules.mmd"] = package_flowchart(
        packages, pkg, "Package-level import graph: modules collapsed onto their "
                       "containing package; edge label = number of module-level import edges.")
    cycle_nodes = [n for scc in all_metrics["nontrivial_sccs"]["members"] for n in scc]
    if cycle_nodes:
        files["modules-cycles.mmd"] = module_flowchart(
            modules, cycle_nodes, pkg,
            "Modules in nontrivial strongly connected components (import cycles), "
            "grouped by package. Dashed: edge made only of function-scope or "
            "TYPE_CHECKING imports.",
            group_by=lambda m: containing_package(m, modules))

    # -- class diagrams --
    in_hierarchy = sorted({c for (s, t, k) in classes.edges if k == "inherits" for c in (s, t)})
    files["classes.mmd"] = class_diagram(
        classes, in_hierarchy, pkg,
        "Classes that take part in an inheritance edge between analysed classes, "
        "with the functions defined in each class body.")
    by_package: dict[str, list[str]] = {}
    for cid, attrs in classes.nodes.items():
        info = project.modules[attrs["module"]]
        owner = info.name if info.is_package else info.name.rpartition(".")[0]
        by_package.setdefault(owner, []).append(cid)
    for owner, members in sorted(by_package.items()):
        files[f"classes/{owner}.mmd"] = class_diagram(
            classes, members, pkg, f"All classes defined in package {owner}.")

    # -- call diagrams --
    scoped_summary = {}
    for name, roots in sorted(opts.call_roots.items()):
        sub = scoped(calls, roots, opts.call_depth)
        unbounded = scoped(calls, roots, max_depth=10**9)
        files[f"calls/{name}.mmd"] = call_flowchart(
            sub, pkg, f"Static call graph from {', '.join(roots)}, depth <= {opts.call_depth}. "
                      "Solid: call/instantiate/__init__/super. Dashed: self-dispatch and "
                      "possible overrides. Dashed border: node with further calls beyond the depth cut.",
            roots)
        scoped_summary[name] = {
            "roots": roots, "max_depth": opts.call_depth,
            "nodes": len(sub.nodes), "edges": len(sub.edges),
            "truncated_nodes": sum(1 for a in sub.nodes.values() if a["truncated"]),
            "reachable_nodes_unbounded": len(unbounded.nodes),
        }

    # -- metrics --
    categories: dict[str, int] = {}
    for info in project.modules.values():
        categories[info.category] = categories.get(info.category, 0) + 1
    edge_kinds: dict[str, int] = {}
    for (_s, _t, k) in calls.edges:
        edge_kinds[k] = edge_kinds.get(k, 0) + 1
    scope_counts: dict[str, int] = {}
    for attrs in modules.edges.values():
        key = "+".join(attrs["scopes"])
        scope_counts[key] = scope_counts.get(key, 0) + 1
    external_bases: dict[str, int] = {}
    for attrs in classes.nodes.values():
        for base in attrs["external_bases"]:
            external_bases[base] = external_bases.get(base, 0) + 1

    metrics = {
        "tool": {"name": "tools.architecture", "version": TOOL_VERSION,
                 "generator_commit": opts.generator_commit,
                 "python": f"{sys.version_info.major}.{sys.version_info.minor}",
                 "grimp": metadata.version("grimp"),
                 "networkx": metadata.version("networkx")},
        "source": {"src": opts.src, "package": pkg, "commit": opts.source_commit},
        "inclusion": {
            "modules_discovered": len(project.modules),
            "modules_in_graph": len(modules.nodes),
            "excluded_modules": excluded_modules(project, modules),
            "module_categories": dict(sorted(categories.items())),
            "reexport_modules": sorted(m for m, i in project.modules.items()
                                       if i.category == "reexport"),
            "dynamic_import_sites": {m: i.dynamic_import_calls for m, i in
                                     sorted(project.modules.items()) if i.dynamic_import_calls},
        },
        "module_graph": {
            "edge_scopes": dict(sorted(scope_counts.items())),
            "all_imports": all_metrics,
            "import_time": describe(import_time.to_networkx()),
        },
        "package_graph": {
            "intra_package_module_edges": sum(a["internal_edges"] for a in packages.nodes.values()),
            **describe(packages.to_networkx()),
        },
        "class_graph": {
            "classes": len(classes.nodes),
            "inherits_edges": len(classes.edges_of_kind("inherits")),
            "nests_edges": len(classes.edges_of_kind("nests")),
            "external_bases": dict(sorted(external_bases.items())),
        },
        "call_graph": {
            "nodes": len(calls.nodes),
            "edges_by_kind": dict(sorted(edge_kinds.items())),
            "call_sites": dict(sorted(call_totals.items())),
            "scoped": scoped_summary,
        },
    }
    files["metrics.json"] = dumps(metrics)
    files["metrics.md"] = render_metrics_md(metrics, opts)
    files["README.md"] = render_readme(metrics, opts, sorted([*files, "README.md"]),
                                       GENERATED_MARKER, FROZEN_MARKER)
    return files


# -- git provenance --------------------------------------------------------
def _git(root: Path, *args: str) -> str:
    return subprocess.run(["git", *args], cwd=root, check=True, capture_output=True,
                          text=True).stdout.strip()


def verify_source_commit(root: Path, rev: str, src: str, package: str) -> str:
    """Full sha of ``rev``; fails unless the analysed tree is exactly that commit's."""
    sha = _git(root, "rev-parse", "--verify", f"{rev}^{{commit}}")
    path = f"{src}/{package}"
    if subprocess.run(["git", "diff", "--quiet", sha, "--", path], cwd=root).returncode != 0:
        raise SystemExit(f"{path} differs from {rev}; refusing to label the output with it")
    stray = [p for p in _git(root, "ls-files", "--others", "--", path).splitlines()
             if p.endswith(".py")]
    if stray:
        raise SystemExit(f"untracked/ignored .py files under {path} are not in {rev}: {stray}")
    return sha


def generator_commit(root: Path) -> str:
    tool = "tools/architecture"
    if _git(root, "status", "--porcelain", "--", tool):
        raise SystemExit(f"{tool} has uncommitted changes; commit the generator first")
    return _git(root, "log", "-1", "--format=%H", "--", tool)


# -- file IO ---------------------------------------------------------------
def _read(path: Path) -> bytes | None:
    return path.read_bytes() if path.is_file() else None


def check(files: dict[str, str], out: Path) -> list[str]:
    """Differences between rendered ``files`` and the directory ``out``."""
    problems = []
    for rel, text in sorted(files.items()):
        current = _read(out / rel)
        if current is None:
            problems.append(f"missing: {rel}")
        elif current != text.encode("utf-8"):
            problems.append(f"differs: {rel}")
    if out.is_dir():
        for path in sorted(out.rglob("*")):
            rel = path.relative_to(out).as_posix()
            if path.is_file() and rel not in files:
                problems.append(f"unexpected: {rel}")
    return problems


def write(files: dict[str, str], out: Path, overwrite_frozen: bool) -> None:
    readme = _read(out / "README.md")
    if readme is not None:
        text = readme.decode("utf-8", "replace")
        if FROZEN_MARKER in text and not overwrite_frozen:
            raise SystemExit(f"{out} is a frozen snapshot; use --check to verify it "
                             "(or --overwrite-frozen if you really mean to replace it)")
        if GENERATED_MARKER not in text:
            raise SystemExit(f"{out}/README.md was not written by this tool; refusing to overwrite")
        for path in sorted(out.rglob("*"), reverse=True):
            rel = path.relative_to(out).as_posix()
            if path.is_file() and rel not in files:
                path.unlink()
            elif path.is_dir() and not any(path.iterdir()):
                path.rmdir()
    elif out.exists() and any(out.iterdir()):
        raise SystemExit(f"{out} exists, is not empty, and has no generated README; refusing")
    for rel, text in sorted(files.items()):
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m tools.architecture.generate",
                                     description=__doc__.split("\n\n")[0])
    parser.add_argument("--src", default="src", help="source root, relative to the repo root")
    parser.add_argument("--package", default="tropoi", help="root package to analyse")
    parser.add_argument("--out", default="docs/architecture/current",
                        help="output directory, relative to the repo root")
    parser.add_argument("--title", default="current", help="snapshot title used in the README")
    parser.add_argument("--call-root", action="append", default=[], metavar="NAME=QUALNAME",
                        help="scoped call graph root (repeatable; replaces the defaults)")
    parser.add_argument("--call-depth", type=int, default=DEFAULT_CALL_DEPTH)
    parser.add_argument("--source-commit", metavar="REV",
                        help="verify that the analysed source equals REV and record its sha")
    parser.add_argument("--freeze", action="store_true",
                        help="mark the output as a frozen historical snapshot "
                             "(requires --source-commit and a committed generator)")
    parser.add_argument("--overwrite-frozen", action="store_true")
    parser.add_argument("--check", action="store_true",
                        help="compare with the files on disk instead of writing; exit 1 if stale")
    args = parser.parse_args(argv)

    roots: dict[str, list[str]] = {}
    for item in args.call_root:
        name, sep, qual = item.partition("=")
        if not sep or not name or not qual:
            parser.error(f"--call-root expects NAME=QUALNAME, got {item!r}")
        roots.setdefault(name, []).append(qual)
    if args.freeze and not args.source_commit:
        parser.error("--freeze requires --source-commit")

    command = ["python -m tools.architecture.generate"]
    for flag, value, default in (("--src", args.src, "src"), ("--package", args.package, "tropoi"),
                                 ("--out", args.out, "docs/architecture/current"),
                                 ("--title", args.title, "current"),
                                 ("--call-depth", args.call_depth, DEFAULT_CALL_DEPTH),
                                 ("--source-commit", args.source_commit, None)):
        if value != default:
            command.append(f"{flag} {value!s}" if " " not in str(value) else f'{flag} "{value}"')
    command.extend(f"--call-root {item}" for item in args.call_root)
    if args.freeze:
        command.append("--freeze")

    opts = Options(src=args.src, package=args.package, out=args.out, title=args.title,
                   call_roots=roots or dict(DEFAULT_CALL_ROOTS), call_depth=args.call_depth,
                   freeze=args.freeze, command=" ".join(command))
    if args.source_commit:
        opts.source_commit = verify_source_commit(REPO_ROOT, args.source_commit,
                                                  args.src, args.package)
    if args.freeze:
        opts.generator_commit = generator_commit(REPO_ROOT)

    files = render(opts)
    out = REPO_ROOT / args.out
    if args.check:
        problems = check(files, out)
        for line in problems:
            print(line, file=sys.stderr)
        print(f"{args.out}: {'stale' if problems else 'up to date'} ({len(files)} files)")
        return 1 if problems else 0
    write(files, out, args.overwrite_frozen)
    print(f"{args.out}: wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
