"""Mermaid renderers for the neutral graph model.

Identifiers are an injective, deterministic encoding of the node name
(:func:`node_id`), so adding or removing an unrelated node never renames the
others and Mermaid keywords such as ``end`` cannot collide with a node id.
Human-readable text goes into quoted labels, escaped by :func:`label`.
"""
from __future__ import annotations

from collections import defaultdict

from . import TOOL_VERSION
from .model import Graph

HEADER = f"%% Generated by tools.architecture {TOOL_VERSION}. Do not edit by hand."


def node_id(name: str, prefix: str = "n") -> str:
    """Injective map from an arbitrary string to a Mermaid-safe identifier.

    Letters and digits pass through; ``_`` becomes ``__``; ``.`` becomes
    ``_o``; any other character becomes ``_x<hex>_``.
    """
    out = [prefix, "_"]
    for ch in name:
        if ch.isascii() and ch.isalnum():
            out.append(ch)
        elif ch == "_":
            out.append("__")
        elif ch == ".":
            out.append("_o")
        else:
            out.append(f"_x{ord(ch):x}_")
    return "".join(out)


_ESCAPES = {'"': "#quot;", "<": "#lt;", ">": "#gt;", "#": "#35;", "|": "#124;",
            "[": "#91;", "]": "#93;", "{": "#123;", "}": "#125;", "\n": " "}


def label(text: str) -> str:
    """Quoted Mermaid label text with Mermaid-significant characters escaped."""
    return '"' + "".join(_ESCAPES.get(ch, ch) for ch in text) + '"'


def member_text(text: str) -> str:
    """Unquoted classDiagram member text: Mermaid reads ``_x_`` as emphasis
    (``__init__`` would render as bold "init"), so ``_`` is written as an
    entity along with the other Mermaid-significant characters."""
    return "".join("#95;" if ch == "_" else _ESCAPES.get(ch, ch) for ch in text)


def _lines(*parts: str) -> str:
    return "\n".join(parts) + "\n"


def _short(name: str, root: str) -> str:
    """Drop the common root prefix from a dotted name for display."""
    return name[len(root) + 1:] if name.startswith(root + ".") else name


# -- module / package graphs ----------------------------------------------
def package_flowchart(agg: Graph, root: str, title: str) -> str:
    """Package-level import graph; edge labels count merged module edges."""
    out = [HEADER, f"%% {title}", "flowchart LR"]
    for pkg in sorted(agg.nodes):
        attrs = agg.nodes[pkg]
        count = attrs["modules"]
        name = pkg if pkg == root else _short(pkg, root)
        text = f"{name} ({count} module{'' if count == 1 else 's'})"
        out.append(f"    {node_id(pkg)}[{label(text)}]")
    for (s, t, _k) in sorted(agg.edges):
        count = agg.edges[(s, t, _k)]["module_edges"]
        out.append(f"    {node_id(s)} -->|{count}| {node_id(t)}")
    return _lines(*out)


def module_flowchart(graph: Graph, nodes: list[str], root: str, title: str,
                     group_by) -> str:
    """Module-level flowchart restricted to ``nodes``, grouped into subgraphs.

    ``group_by(module) -> group name``. Edges carrying only ``function`` or
    ``type_checking`` statements are drawn dashed and labelled with their scope.
    """
    keep = set(nodes)
    groups: dict[str, list[str]] = defaultdict(list)
    for n in sorted(keep):
        groups[group_by(n)].append(n)
    out = [HEADER, f"%% {title}", "flowchart LR"]
    for group in sorted(groups):
        out.append(f"    subgraph {node_id(group, 'g')}[{label(_short(group, root) if group != root else root)}]")
        for n in groups[group]:
            out.append(f"        {node_id(n)}[{label(_short(n, root))}]")
        out.append("    end")
    for (s, t, k) in sorted(graph.edges):
        if s in keep and t in keep:
            scopes = graph.edges[(s, t, k)]["scopes"]
            if "module" in scopes:
                out.append(f"    {node_id(s)} --> {node_id(t)}")
            else:
                out.append(f"    {node_id(s)} -.->|{'+'.join(scopes)}| {node_id(t)}")
    return _lines(*out)


# -- class graph -----------------------------------------------------------
_MEMBER_MARK = {"classmethod": "$", "staticmethod": "$"}


def class_diagram(graph: Graph, classes: list[str], root: str, title: str,
                  with_members: bool = True) -> str:
    """Mermaid ``classDiagram`` of the given classes and edges among them."""
    keep = set(classes)
    out = [HEADER, f"%% {title}", "classDiagram", "    direction LR"]
    for cid in sorted(keep):
        attrs = graph.nodes[cid]
        text = f"{attrs['qualname']} ({_short(attrs['module'], root)})"
        out.append(f"    class {node_id(cid, 'c')}[{label(text)}]")
        if with_members:
            for member in attrs["members"]:
                suffix = _MEMBER_MARK.get(member["kind"], "")
                shown = f"{member['name']}()" if member["kind"] != "property" else member["name"]
                out.append(f"    {node_id(cid, 'c')} : +{member_text(shown)}{suffix}")
        for base in attrs["external_bases"]:
            out.append(f"    {node_id(cid, 'c')} : external base {member_text(base)}")
    for (s, t, k) in sorted(graph.edges):
        if s in keep and t in keep:
            arrow = "<|--" if k == "inherits" else "*--"
            # Mermaid draws "Parent <|-- Child"; our edges run child -> parent.
            out.append(f"    {node_id(t, 'c')} {arrow} {node_id(s, 'c')}")
    return _lines(*out)


# -- call graphs -----------------------------------------------------------
_ARROWS = {
    "call": "-->",
    "instantiate": "-->|instantiate|",
    "constructor": "-->|__init__|",
    "super": "-->|super|",
    "self": "-.->|self|",
    "override": "-.->|override?|",
}


def call_flowchart(sub: Graph, root: str, title: str, roots: list[str]) -> str:
    """Scoped call graph grouped by module; dispatch-dependent edges dashed."""
    out = [HEADER, f"%% {title}", "flowchart LR"]
    by_module: dict[str, list[str]] = defaultdict(list)
    for n in sorted(sub.nodes):
        by_module[sub.nodes[n]["module"]].append(n)
    for module in sorted(by_module):
        out.append(f"    subgraph {node_id(module, 'g')}[{label(_short(module, root))}]")
        for n in by_module[module]:
            attrs = sub.nodes[n]
            if attrs["type"] == "class":
                out.append(f"        {node_id(n)}{{{{{label(attrs['qualname'])}}}}}")
            else:
                out.append(f"        {node_id(n)}[{label(attrs['qualname'] + '()')}]")
        out.append("    end")
    for (s, t, k) in sorted(sub.edges):
        out.append(f"    {node_id(s)} {_ARROWS[k]} {node_id(t)}")
    out.append("    classDef root stroke-width:3px")
    out.append("    classDef truncated stroke-dasharray:4 3")
    for r in sorted(roots):
        out.append(f"    class {node_id(r)} root")
    for n in sorted(sub.nodes):
        if sub.nodes[n].get("truncated"):
            out.append(f"    class {node_id(n)} truncated")
    return _lines(*out)
